---
- name: Grant pgopal sudo access to su - eomadmin
  become: true
  hosts: all
  gather_facts: false
  tasks:
    - name: add Ticket No. entry to /etc/sudoers
      lineinfile:
        path: /etc/sudoers
        line: "## Ticket 12345-67890"
        state: present
    - name: add cooluser entry to /etc/sudoers
      lineinfile:
        path: /etc/sudoers
        line: "cooluser  ALL=(ALL) NOPASSWD: /bin/su - cooladmin"
        state: present
