---
- name: Grant pgopal sudo access to su - eomadmin
  become: true
  hosts: all
  gather_facts: false
  tasks:
    - name: add Ticket No. entry to /etc/sudoers
      lineinfile:
        path: /etc/sudoers
        line: "## Ticket 200924-02618"
        state: present
    - name: add pgopal entry to /etc/sudoers
      lineinfile:
        path: /etc/sudoers
        line: "pgopal  ALL=(ALL) NOPASSWD: /bin/su - eomadmin"
        state: present
