---
- name: copy vrm cert 
  become: true
  hosts: all
  tasks:
    - name: ensure dir /home/rack/scripts exists
      file:
        path: /home/rack/scripts
        state: directory
        owner: rack
        group: rack
        mode: 0750
    - name: copy script to /home/rack/scripts/vormetric_cert.sh
      copy:
        src: vormetric_cert.sh
        dest: /home/rack/scripts/vormetric_cert.sh
        owner: rack
        group: rack
        mode: 0740
    - name: ensure /var/spool/cron/root exists
      copy:
        dest: /var/spool/cron/root
        content: ""
        force: no
        owner: root
        group: root
        mode: 0600
    - name: echo in cron job
      #command: echo '0 0 1 * * /home/rack/scripts/vormetric_cert.sh' > /var/spool/cron/root 
      lineinfile:
        path: /var/spool/cron/root
        line: 0 0 1 * * /home/rack/scripts/vormetric_cert.sh 
        state: present
    - name: Verify cron job
      command: crontab -u root -l
      register: root_crons
    - name: print verification
      debug:
        msg: "{{ root_crons }}"
