---
- name: host setup
  hosts: localhost
  vars:
    inventory: /etc/ansible/hosts
  tasks:
  - fail:
      msg: failure to define vars newhost or newhostip
    when: (newhost is not defined) or (newhostip is not defined)
  - name: add new host to inventory
    lineinfile:
      path: "{{ inventory }}"
      line: "{{ newhost }}"
  - name: add new host to '/etc/hosts'
    lineinfile:
      path: /etc/hosts
      line: "{{ newhostip }}  {{ newhost }}"
  tags: addhost

- name: ansible user setup
  hosts: "{{ newhost }}"
  remote_user: root
  become: false
  tasks:
  - name: create ansible user
    user:
      name: ansible
  - name: ansible user pw
    command: 'echo password | passwd --stdin ansible'
  - name: ansible user sudo privs
    lineinfile:
      path: /etc/sudoers
      line: 'ansible    ALL=(ALL)       NOPASSWD: ALL'
  - name: ansible user key auth - dir
    file:
      path: /home/ansible/.ssh
      owner: ansible
      group: ansible
  - name: ansible user key auth
    copy:
      src: /home/ansible/.ssh/id_rsa.pub
      dest: /home/ansible/.ssh/authorized_keys
  tags: adduser

- name: register and set up repos
  hosts: "{{ newhost }}"
  vars_files: vars/rhsm
  tasks:
  - name: register & subscribe {{ newhost }}
    redhat_subscription:
      username: "{{ rhsm_user }}"
      password: "{{ rhsm_pass }}"
      auto_attach: true
  - name: configure additional repo access
    rhsm_repository:
      name:
      - rhel-8-for-x86_64-appstream-rpms
      - rhel-8-for-x86_64-baseos-rpms
      - ansible-2.8-for-rhel-8-x86_64-rpms
      - ansible-2.8-for-rhel-8-x86_64-debug-rpms
      state: present
  tags: registerhost
