---
- name:  Post Online Linux Checks - Customer Production
  hosts: all
  become: true
  tasks:
  - name: Disable ipv6
    sysctl:
      name: "{{ item }}"
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
    with_items:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6
      - net.ipv6.conf.lo.disable_ipv6
      - net.ipv6.conf.eth0.disable_ipv6
      - net.ipv6.conf.eth1.disable_ipv6
