---
- name:  Post Online Linux Checks - Production
  hosts: all
  become: true
  tasks:
  - name: A) Set timezone to America/New York
    timezone:
      name: America/New_York

  - name: C) Check hostname
    debug:
    var: ansible_facts['ansible_hostname'] 

  - name: D) Add /etc/hosts markers
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
      state: present
    with_items:
      - '#App'
      - '#PDP DMS Info'
      - '#NFS'

  - name: D) Verify / Add App entries in /etc/hosts
    lineinfile:
      path: /etc/hosts
      insertafter: '#App'
      backup: true
      line: "{{ item }}"
      state: present
    with_items:
      - '192.168.102.4 123456-private.domain.com'
      - '192.168.102.5 123456-private.domain.com'
      - '192.168.102.6 123456-private.domain.com'
      - '192.168.102.7 123456-private.domain.com'
      - '192.168.102.15 123456-private.domain.com'
      - '192.168.102.16 123456-private.domain.com'
      - '192.168.102.8 123456-private.domain.com'
      - '192.168.102.9 123456-private.domain.com'
      - '192.168.102.10 123456-private.domain.com'
      - '192.168.102.11 123456-private.domain.com'
      - '192.168.102.12 123456-private.domain.com'
      - '192.168.102.13 123456-private.domain.com'
      - '192.168.102.14 123456-private.domain.com'
      
  - name: D) Verify / Add PDP DMS Info entries in /etc/hosts
    lineinfile:
      path: /etc/hosts
      insertafter: '#PDP DMS Info'
      line: "{{ item }}"
      state: present
    with_items:
      - '172.27.16.14    123456-private.domain.com'' 
      - '172.27.16.15    123456-private.domain.com'' 
      - '172.28.16.194   123456-private.domain.com'' 
      - '172.28.16.195   123456-private.domain.com''

  - name: D) Verify / Add PDP NFS Info entries in /etc/hosts
    lineinfile:
      path: /etc/hosts
      insertafter: '#NFS'
      line: "{{ item }}"
      state: present
    with_items:
      - '192.168.103.30 123456-private.domain.com'' 
      - '192.168.103.35 123456-private.domain.com''

  - name: E) DNS name server settings -- add entries for 192.168.109.31, 192.168.109.4
    lineinfile:
      path: /etc/resolv.conf
      line: "{{ item }}"
      backup: true
    with_items:
      - 'nameserver 192.168.109.31'    
      - 'nameserver 192.168.109.4'    
  
  #- name: F) Check IP6 has been removed
  #  command: ifconfig | grep inet6
  #  register: ip6_out

  #- name: F) IP6 Output
  #  debug:
  #    var: "ip6_out"

  - name: G) Create persistent NFS mount - Install nfs-utils
    yum:
      name: nfs-utils
      state: latest

  - name: G) Create persistent NFS mount - create mount points
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /shared
      - /mnt/nfs-logs

  - name: G) Create persistent NFS mount - /shared
    mount:
      path: /shared
      src: 192.168.103.30:/san/nfs-fs/exports/shared
      fstype: nfs4
      state: mounted
      opts:   retry=600,_netdev,vers=4,proto=tcp,hard,sec=sys,timeo=150,retrans=600,relatime
  
  - name: G) Create persistent NFS mount - /mnt/nfs-logs
    mount:
      path: /mnt/nfs-logs
      src: 192.168.103.35:/san/nfs-log-fs/logs
      fstype: nfs4
      state: mounted
      opts: retry=600,hard,noatime,_netdev       

  - name: H) Change SMTP Postfix Config
    copy:
      src: main.cf
      dest: /etc/postfix/main.cf
      backup: true

  - name: H) Change SMTP Postfix Config - restart postfix
    service:
      name: postfix
      state: restarted
